#!/bin/sh

### BEGIN INIT INFO
# Provides:          jjrobotd
# Required-Start:    docker
# Required-Stop:     docker
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       JJRobot Daemon
### END INIT INFO

JJROBOTCTL=/usr/local/bin/jjrobotctl

case "$1" in
        start|restart)
                $JJROBOTCTL restart
        ;;
        stop)
                $JJROBOTCTL down

                docker ps -a -f name=jjrobotd | grep jjrobotd
                if [ $? -eq 0 ]; then
                        docker rm -f jjrobotd
                fi
        ;;
        *)
        echo "Usage: $0 {start|stop|restart}"
esac
